version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - nw_app

  nginx:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nw_app

networks:
  nw_app:
    driver: bridge